<?php

namespace App\Models;

// Note: this file replaces the default app/Models/User.php generated by Laravel.
// Keep Authenticatable, HasFactory, Notifiable — only additions are role_id,
// is_active, SoftDeletes, and the relationships below.

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable, SoftDeletes;

    protected $fillable = [
        'name',
        'email',
        'password',
        'role_id',
        'is_active',
    ];

    protected $hidden = [
        'password',
        'remember_token',
    ];

    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
            'is_active' => 'boolean',
        ];
    }

    public function role(): BelongsTo
    {
        return $this->belongsTo(Role::class);
    }

    // Reverse relationships — actions this user has performed across modules.
    public function createdProductionOrders(): HasMany
    {
        return $this->hasMany(ProductionOrder::class, 'created_by');
    }

    public function productionRecords(): HasMany
    {
        return $this->hasMany(ProductionRecord::class, 'recorded_by');
    }

    public function inspectionsPerformed(): HasMany
    {
        return $this->hasMany(QualityInspection::class, 'inspector_id');
    }

    public function defectsDetected(): HasMany
    {
        return $this->hasMany(QualityDefect::class, 'detected_by');
    }

    public function correctiveActionsResponsible(): HasMany
    {
        return $this->hasMany(CorrectiveAction::class, 'responsible_user_id');
    }

    public function stockMovements(): HasMany
    {
        return $this->hasMany(StockMovement::class, 'performed_by');
    }

    public function activityLogs(): HasMany
    {
        return $this->hasMany(ActivityLog::class);
    }

    public function hasRole(string $roleName): bool
    {
        return $this->role?->name === $roleName;
    }
}
